language: node_js
node_js:
- 0.1

env:
  matrix:
  - BROWSER=chrome  BVER=stable
  - BROWSER=chrome  BVER=beta
  - BROWSER=chrome  BVER=unstable
  - BROWSER=firefox BVER=stable
  - BROWSER=firefox BVER=beta
  - BROWSER=firefox BVER=nightly

global:
  - secure: aNlM6xaQ8q0XotMnY3UJRpZuEXSHABxYag1mhxVd7QiBtnS9McD++xyeW71aBlOToMQD+Er/ZJoX5ZVaXefW34CeHEKR/IVggUIevyO2zIQE/WAK6PjwFMMryQcJSSUfBN8+8nbLOEVv4fpw3GuObOVuDC6ZsbOkgzkVEPOp9I0=
  - secure: HpSaah4cOX/OxbMvzJ9OLvHKP38cah1DRB6LBWjKsUMKuT/Jq2kb+w4cF2RSUv96sxmLNITiwUg1azSZvu7gd1qU8BMYPZzD0qiYkoVt3QzXp1MrvvGcvaYpgE7NPHSTbE/DSDi29r/CKWcuquX22j4hh6FplXxgezZaEbz0y8Y=

matrix:
  fast_finish: true

  allowed_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly

before_install:
  - mkdir -p .travis
  - curl -s https://codeload.github.com/rtc-io/webrtc-testing-on-travis/tar.gz/master | tar -xz --strip-components=1 --directory .travis
  - ./.travis/setup.sh
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io
